### ISSUE TITLE
llama-token.npy issue

### ISSUE THREAD

**Issue by nemesisXX** [Jyonn/Legommenders#11]
Hello, 
we try to replicate the ONCE experiment and start with the training preparation part. However, when we ran the worker.py, we realized we didn't have a llama-token.npy file. We have detected the tokenized dataset, and there's no file called llama-token.npy as well. Is there any doc missing here? Or is there any python files that could help us generate llama-token.npy? thank you.

**Comment by Jyonn** [comment]
You can use the following script to extract token embeddings:

```
import numpy as np
from transformers import LlamaModel

pretrained_dir = '/home/data1/qijiong/llama-7b'
device = 'cuda:1'

# Load pre-trained model (weights)
model = LlamaModel.from_pretrained(pretrained_dir).to(device)  # type: LlamaModel
print(len(model.layers))

# Put the model in "evaluation" mode, meaning feed-forward operation.
model.eval()

embeds = model.embed_tokens.weight.cpu().detach().numpy()
np.save('llama-token.npy', embeds)

```
