### ISSUE TITLE
Goodreads dataset no "title" column

### ISSUE THREAD

**Issue by nemesisXX** [Jyonn/Legommenders#12]
Hi there,
When I executed the worker.py on the tokenized Goodreads dataset, I checked the meta.data.json and found that there's no column named "title". So when the part of the depot.get_vocab in the file embedding_hub.py is called, it shows "KeyError: title", but I didn't find anywhere I could modify the default columns name. Could you please give me some instructions? Thank you so much.

**Comment by Jyonn** [comment]
Hi 

You can use command ‘unitok /path/to/goodreads/book’ to check prepared columns. The correct column name may be ‘name’ rather than ‘title’ for this dataset.

**Comment by Jyonn** [comment]
Hi, you can use the `title-bert` or `title-llama` in this case. 
<img width="635" alt="image" src="https://github.com/user-attachments/assets/8bb7c614-661c-478d-8799-5b82e1d83164">
