### ISSUE TITLE
citation for this tool

### ISSUE THREAD

**Issue by chiyuzhang94** [Jyonn/Legommenders#4]
Hi @Jyonn ,

I would like to know if you have any citation for this tool. I will cite it in my works. 

Best,
Chiyu

**Comment by Jyonn** [comment]
Hi Chiyu,

For now we do not have related papers or sites to introduce our framework, which is not fully prepared to the public, with little comments and guidance. Sorry for the inconvenience during using. 

The following is one option, or you can directly use footnote to link to our GitHub.

```
@online{legommenders,
  author = {Liu, Qijiong},
  title = {Legommenders: A Modular Framework for Recommender Systems},
  year = {2023},
  url = {https://github.com/Jyonn/Legommenders}
}
```

Thanks for your question.
